In [2]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cross_validation import cross_val_score
from sklearn.grid_search import GridSearchCV
import numpy as np
from sklearn.cross_validation import train_test_split, cross_val_score
import cPickle as pickle

In [2]:
np_lst = pd.read_csv('np_lst.txt', header=None)[0].values

In [3]:
np_lst

array(['biking_a.npy', 'biking_b.npy', 'cooking_a.npy', 'cooking_b.npy',
       'fashion_a.npy', 'fashion_b.npy', 'fitness_a.npy', 'fitness_b.npy',
       'gardening_a.npy', 'gardening_b.npy', 'hiking_a.npy',
       'hiking_b.npy', 'hunting_fishing_a.npy', 'hunting_fishing_b.npy',
       'kids_a.npy', 'kids_b.npy', 'pets_a.npy', 'pets_b.npy',
       'social_out_a.npy', 'social_out_b.npy', 'summer_fun_a.npy',
       'summer_fun_b.npy', 'winter_sports_a.npy', 'winter_sports_b.npy'], dtype=object)

In [4]:
np_path = '../numpiis/'
feat_array = []
for i, feats in enumerate(np_lst):
    if '_a' in feats:
        feat_array.append(np.load(np_path+feats))
    else:
        feat_array[-1] = np.vstack([feat_array[-1], np.load(np_path+feats)])

In [5]:
len(feat_array[0])

1097

In [6]:
label_lst = []
for i, feats in enumerate(feat_array):
    label_lst.append(i*np.ones(len(feats)))

labels = np.hstack(label_lst)

In [7]:
features = np.vstack(feat_array)

In [8]:
features.shape

(14454, 4096)

In [9]:
labels.shape

(14454,)

In [10]:
X = features
y = labels

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [12]:
mod_logit = LogisticRegression()

In [13]:
score_lst = []
score_lst.append(cross_val_score(mod_logit, X, y))
print np.array(score_lst).mean()    

0.738338062202


In [15]:
fitted_logit = mod_logit.fit(X, y)

In [22]:
with  open("mod_logit.pkl", 'w') as f:
    pickle.dump(fitted_logit, f)

In [3]:
with open('mod_logit.pkl') as m_un:
    flp = pickle.load(m_un)

In [4]:
import glob

In [8]:
sorted([im_f for im_f in glob.glob('../../inta_profs/senabrew/*.jpg')])

['../../inta_profs/senabrew/10175115_598882023576242_1069951670_n.jpg',
 '../../inta_profs/senabrew/10598296_1578985549008153_1710632587_n.jpg',
 '../../inta_profs/senabrew/10611244_510995049102857_925135978_n.jpg',
 '../../inta_profs/senabrew/10724050_126755870998191_242320420_n.jpg',
 '../../inta_profs/senabrew/10724909_980562415310194_1203044063_n.jpg',
 '../../inta_profs/senabrew/10731983_868124916610507_284026142_n.jpg',
 '../../inta_profs/senabrew/10809569_1591613731069198_1747942771_n.jpg',
 '../../inta_profs/senabrew/10817547_736595463093052_516191007_n.jpg',
 '../../inta_profs/senabrew/10817983_1527442354174082_1598704421_n.jpg',
 '../../inta_profs/senabrew/10848263_1376282129336019_1028462710_n.jpg',
 '../../inta_profs/senabrew/10848366_845258572161140_963886411_n.jpg',
 '../../inta_profs/senabrew/10852555_513529112122642_1375733516_n.jpg',
 '../../inta_profs/senabrew/10860182_301041086773544_1955105038_n.jpg',
 '../../inta_profs/senabrew/10864667_531767890260210_553267219_n.

In [6]:
flp.predict(np.load('senabrew_c.npy'))

array([  9.,   1.,   5.,   5.,  10.,   0.,   6.,   3.,   9.,  11.,  11.,
         4.,   1.,   6.,   2.,   5.,   3.,   9.,   3.,  10.,   5.,   1.,
         2.,   6.,   9.,  10.,  11.,   2.,   1.,   0.,   1.,   9.,  11.,
         8.,   4.,   0.,   4.,   2.,   4.,   8.,   6.,   5.,   6.,   9.,
         1.,   9.,   0.,   9.,   4.,   0.,   1.,   6.,  11.,   6.,   1.,
         3.,   5.,   1.,   5.,   8.,   2.,   9.,   2.,   5.,   3.,   1.,
         2.,   1.,   0.,   9.,   8.,   6.])

In [7]:
flp.predict(np.load('senabrew_d.npy'))

array([  9.,   1.,   5.,   5.,  10.,   0.,   6.,   3.,   9.,  11.,  11.])

In [8]:
flp.predict(np.load('senabrew_modded.npy'))

array([ 11.,   5.,   5.,   3.,   1.,   2.,   1.,   2.,   9.,   3.,   9.])

In [52]:
mod_RF = RandomForestClassifier(n_estimators=200)

In [53]:
score_lst = []
score_lst.append(cross_val_score(mod_RF, X, y))
print np.array(score_lst).mean()  

0.722909874312


In [54]:
mod_svm = SVC(kernel='linear')

In [55]:
score_lst = []
score_lst.append(cross_val_score(mod_svm, X, y))
print np.array(score_lst).mean() 

0.752865007745


In [59]:
mod_gbc = GradientBoostingClassifier()

In [2]:
# score_lst = []
# score_lst.append(cross_val_score(mod_gbc, X, y))
# print np.array(score_lst).mean() 

In [56]:
score_lst = []
score_lst.append(cross_val_score(mod_logit, X, y,scoring='mean_squared_error') )
print np.array(score_lst).mean() 

-5.69939780715


In [57]:
score_lst = []
score_lst.append(cross_val_score(mod_svm, X, y,scoring='mean_squared_error') )
print np.array(score_lst).mean() 

-5.58323709763
